define (problem quest_3)
(:domain magic-world)
(:objects hero - player object-of-interest - item forbidden-room-object - location forbidden_room_object_of_interest - location professor - npc room-with-secret-object - location room-with_secret_object - location)
(:init
    (at hero room-with-secret-object)
    (is-alive hero)
    (has forbidden_room_object_of_interest hero)
    (vulnerable_to hero professor forbidden_room_object_of_interest)
    (is-alive professor)
    (at professor room-with-secret-object)
    (at object-of-interest room-with-secret-object)
    (connected room-with-secret-object forbidden_room_object_of_interest)
    (is-alive forbidden_room_object_of_interest)
    (connected forbidden_room_object_of_interest room-with_secret_object)
    (has forbidden_room_object_of_interest professor)
    (at forbidden_room_object_of_interest forbidden_room_object_of_interest)
    (locked room-with-secret-object)
    (key-for (item-of 'lockpick) room-with-secret-object)
    (connected room-with_secret_object forbidden_room_object_of_interest)
    (connected forbidden_room_object_of_interest room-with_secret_object)
)
(:goal
    (and
        (has forbidden_room_object_of_interest hero)
    ))
)